/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 2.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios'
import { Configuration } from '../configuration'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from '../base'
import { InlineResponse2007 } from '../models'
import { InlineResponse400 } from '../models'
/**
 * NewsApi - axios parameter creator
 * @export
 */
export const NewsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * ニュースのコンテンツの取得
     * @summary ニュースのコンテンツの取得
     * @param {number} offset 何番目から取得するか
     * @param {number} limit 何個取得するか
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getNews: async (
      offset: number,
      limit: number,
      options: any = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'offset' is not null or undefined
      if (offset === null || offset === undefined) {
        throw new RequiredError(
          'offset',
          'Required parameter offset was null or undefined when calling getNews.',
        )
      }
      // verify required parameter 'limit' is not null or undefined
      if (limit === null || limit === undefined) {
        throw new RequiredError(
          'limit',
          'Required parameter limit was null or undefined when calling getNews.',
        )
      }
      const localVarPath = `/news`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com')
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }
      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      if (offset !== undefined) {
        localVarQueryParameter['offset'] = offset
      }

      if (limit !== undefined) {
        localVarQueryParameter['limit'] = limit
      }

      const query = new URLSearchParams(localVarUrlObj.search)
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key])
      }
      for (const key in options.query) {
        query.set(key, options.query[key])
      }
      localVarUrlObj.search = new URLSearchParams(query).toString()
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * NewsApi - functional programming interface
 * @export
 */
export const NewsApiFp = function (configuration?: Configuration) {
  return {
    /**
     * ニュースのコンテンツの取得
     * @summary ニュースのコンテンツの取得
     * @param {number} offset 何番目から取得するか
     * @param {number} limit 何個取得するか
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getNews(
      offset: number,
      limit: number,
      options?: any,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<InlineResponse2007>
    > {
      const localVarAxiosArgs = await NewsApiAxiosParamCreator(
        configuration,
      ).getNews(offset, limit, options)
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH,
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        }
        return axios.request(axiosRequestArgs)
      }
    },
  }
}

/**
 * NewsApi - factory interface
 * @export
 */
export const NewsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  return {
    /**
     * ニュースのコンテンツの取得
     * @summary ニュースのコンテンツの取得
     * @param {number} offset 何番目から取得するか
     * @param {number} limit 何個取得するか
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getNews(
      offset: number,
      limit: number,
      options?: any,
    ): AxiosPromise<InlineResponse2007> {
      return NewsApiFp(configuration)
        .getNews(offset, limit, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * NewsApi - object-oriented interface
 * @export
 * @class NewsApi
 * @extends {BaseAPI}
 */
export class NewsApi extends BaseAPI {
  /**
   * ニュースのコンテンツの取得
   * @summary ニュースのコンテンツの取得
   * @param {number} offset 何番目から取得するか
   * @param {number} limit 何個取得するか
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof NewsApi
   */
  public getNews(offset: number, limit: number, options?: any) {
    return NewsApiFp(this.configuration)
      .getNews(offset, limit, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
