import { useState } from 'react'
import { Button } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import { LottieControl } from '@/components/atoms/Animation/index'
import styles from '../../styles/Home.module.css'

export default function Home() {
  const [isReverse, setIsReverse] = useState(false)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LottieControl
          width="40px"
          height="40px"
          loop={false}
          isReverse={isReverse}
        />
        <Button onClick={() => setIsReverse(!isReverse)} mt="4">
          click
        </Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
