/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 1.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Author
 */
export interface Author {
  /**
   * 著者名
   * @type {string}
   * @memberof Author
   */
  name: any
  /**
   * 説明
   * @type {string}
   * @memberof Author
   */
  description: any
  /**
   * 画像データ
   * @type {string}
   * @memberof Author
   */
  image: any
  /**
   * 著者ID
   * @type {string}
   * @memberof Author
   */
  id: any
}
