/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 2.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface BlogContent
 */
export interface BlogContent {
  /**
   * タイトル
   * @type {string}
   * @memberof BlogContent
   */
  title: any
  /**
   * ブログID
   * @type {string}
   * @memberof BlogContent
   */
  id: any
  /**
   * 作成日
   * @type {string}
   * @memberof BlogContent
   */
  createdAt: any
  /**
   *
   * @type {Tag}
   * @memberof BlogContent
   */
  tag: any
  /**
   * 画像データ
   * @type {string}
   * @memberof BlogContent
   */
  image?: any
}
