/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 1.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface BlogContentElementReference
 */
export interface BlogContentElementReference {
  /**
   * タイトル
   * @type {string}
   * @memberof BlogContentElementReference
   */
  title?: any
  /**
   * 説明
   * @type {string}
   * @memberof BlogContentElementReference
   */
  description?: any
  /**
   * 画像データ
   * @type {string}
   * @memberof BlogContentElementReference
   */
  image?: any
}
