/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 2.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface BlogContentElement
 */
export interface BlogContentElement {
  /**
   * 要素のタイプ
   * @type {string}
   * @memberof BlogContentElement
   */
  type: any
  /**
   * 文字
   * @type {string}
   * @memberof BlogContentElement
   */
  text: any
  /**
   * 画像データ
   * @type {string}
   * @memberof BlogContentElement
   */
  image: any
  /**
   * URL
   * @type {string}
   * @memberof BlogContentElement
   */
  url: any
  /**
   *
   * @type {BlogContentElementReference}
   * @memberof BlogContentElement
   */
  reference: any
}
