/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 2.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface IndexTitle
 */
export interface IndexTitle {
  /**
   * ラベル
   * @type {string}
   * @memberof IndexTitle
   */
  label: any
  /**
   * タイトルのタイプ
   * @type {string}
   * @memberof IndexTitle
   */
  type: IndexTitleTypeEnum
}

/**
 * @export
 * @enum {string}
 */
export enum IndexTitleTypeEnum {
  H1 = 'h1',
  H2 = 'h2',
  H3 = 'h3',
  H4 = 'h4',
  H5 = 'h5',
  H6 = 'h6',
}
