/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 1.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface InlineResponse2007Data
 */
export interface InlineResponse2007Data {
  /**
   *
   * @type {Array&lt;RoadmapItem&gt;}
   * @memberof InlineResponse2007Data
   */
  schedule?: any
  /**
   *
   * @type {Array&lt;RoadmapItem&gt;}
   * @memberof InlineResponse2007Data
   */
  develop?: any
  /**
   *
   * @type {Array&lt;RoadmapItem&gt;}
   * @memberof InlineResponse2007Data
   */
  merge?: any
}
