/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 1.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface InlineResponse400
 */
export interface InlineResponse400 {
  /**
   * エラーメッセージ
   * @type {string}
   * @memberof InlineResponse400
   */
  message?: any
  /**
   * 成功ならtrueを、失敗ならfalseを返す
   * @type {boolean}
   * @memberof InlineResponse400
   */
  success?: any
}
