/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 1.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface InlineResponse2004Data
 */
export interface InlineResponse2004Data {
  /**
   * タイトル
   * @type {string}
   * @memberof InlineResponse2004Data
   */
  title: any
  /**
   * 画像データ
   * @type {string}
   * @memberof InlineResponse2004Data
   */
  image: any
  /**
   * 作成日
   * @type {string}
   * @memberof InlineResponse2004Data
   */
  createdAt: any
  /**
   * 更新日
   * @type {string}
   * @memberof InlineResponse2004Data
   */
  updatedAt: any
  /**
   *
   * @type {any}
   * @memberof InlineResponse2004Data
   */
  content: any
  /**
   *
   * @type {any}
   * @memberof InlineResponse2004Data
   */
  entry: any | null
  /**
   *
   * @type {any}
   * @memberof InlineResponse2004Data
   */
  asset: any | null
  /**
   *
   * @type {Author}
   * @memberof InlineResponse2004Data
   */
  author: any
  /**
   *
   * @type {InlineResponse2004DataLgtm}
   * @memberof InlineResponse2004Data
   */
  lgtm: any
  /**
   *
   * @type {Array&lt;IndexTitle&gt;}
   * @memberof InlineResponse2004Data
   */
  index: any
  /**
   *
   * @type {Tag}
   * @memberof InlineResponse2004Data
   */
  tag: any
}
