/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 1.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface InlineResponse2003DataPage
 */
export interface InlineResponse2003DataPage {
  /**
   *
   * @type {number}
   * @memberof InlineResponse2003DataPage
   */
  current: any
  /**
   *
   * @type {number}
   * @memberof InlineResponse2003DataPage
   */
  totalCount: any
}
