/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 2.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface InlineResponse2002Data
 */
export interface InlineResponse2002Data {
  /**
   *
   * @type {Array&lt;TimeArchive&gt;}
   * @memberof InlineResponse2002Data
   */
  monthlyArchives: any
  /**
   *
   * @type {Array&lt;TagArchive&gt;}
   * @memberof InlineResponse2002Data
   */
  tagArchives: any
  /**
   *
   * @type {Array&lt;Tag&gt;}
   * @memberof InlineResponse2002Data
   */
  tags: any
}
