/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 1.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface InlineResponse2003Data
 */
export interface InlineResponse2003Data {
  /**
   *
   * @type {Array&lt;BlogContent&gt;}
   * @memberof InlineResponse2003Data
   */
  contents?: any
  /**
   *
   * @type {InlineResponse2003DataPage}
   * @memberof InlineResponse2003Data
   */
  page?: any
}
