/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 2.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 画像データ
 * @export
 * @interface NewsItemImage
 */
export interface NewsItemImage {
  /**
   * URL
   * @type {string}
   * @memberof NewsItemImage
   */
  url?: any
  /**
   * alt
   * @type {string}
   * @memberof NewsItemImage
   */
  alt?: any
}
