/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 2.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface NewsItem
 */
export interface NewsItem {
  /**
   * ID
   * @type {string}
   * @memberof NewsItem
   */
  id: any
  /**
   * 日付
   * @type {string}
   * @memberof NewsItem
   */
  date: any
  /**
   * テキスト
   * @type {string}
   * @memberof NewsItem
   */
  text: any
  /**
   *
   * @type {NewsItemImage}
   * @memberof NewsItem
   */
  image: any
}
