/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 1.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PortfolioShops
 */
export interface PortfolioShops {
  /**
   * 画像データ
   * @type {string}
   * @memberof PortfolioShops
   */
  image: any
  /**
   * タイトル
   * @type {string}
   * @memberof PortfolioShops
   */
  title: any
  /**
   * 説明
   * @type {string}
   * @memberof PortfolioShops
   */
  description: any
  /**
   * リンク
   * @type {string}
   * @memberof PortfolioShops
   */
  link: any | null
}
