/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 1.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PortfolioWorks
 */
export interface PortfolioWorks {
  /**
   * 画像データ
   * @type {string}
   * @memberof PortfolioWorks
   */
  image: any
  /**
   * タイトル
   * @type {string}
   * @memberof PortfolioWorks
   */
  title: any
  /**
   * 説明
   * @type {string}
   * @memberof PortfolioWorks
   */
  description: any
  /**
   * リンク
   * @type {string}
   * @memberof PortfolioWorks
   */
  link?: any | null
  /**
   * githubのリンク
   * @type {string}
   * @memberof PortfolioWorks
   */
  github?: any | null
  /**
   * 製作した年
   * @type {number}
   * @memberof PortfolioWorks
   */
  year: any
}
