/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 1.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface TagArchive
 */
export interface TagArchive {
  /**
   *
   * @type {Tag}
   * @memberof TagArchive
   */
  tag: any
  /**
   * 割合（%）
   * @type {number}
   * @memberof TagArchive
   */
  percentage: any
  /**
   * カウント
   * @type {number}
   * @memberof TagArchive
   */
  count: any
}
