/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 2.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Tag
 */
export interface Tag {
  /**
   * ラベル
   * @type {string}
   * @memberof Tag
   */
  label: any
  /**
   * 色
   * @type {string}
   * @memberof Tag
   */
  color: any
  /**
   * タグID
   * @type {string}
   * @memberof Tag
   */
  tagId: any
  /**
   * ID
   * @type {string}
   * @memberof Tag
   */
  id: any
}
