/* tslint:disable */
/* eslint-disable */
/**
 * ポートフォリオのAPIインタフェース定義
 * ポートフォリオのAPIインタフェース定義
 *
 * OpenAPI spec version: 2.0.0
 * Contact: awpjdmga1943@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface TimeArchive
 */
export interface TimeArchive {
  /**
   * 年月別のアーカイブのラベル
   * @type {string}
   * @memberof TimeArchive
   */
  label: any
  /**
   * カウント
   * @type {number}
   * @memberof TimeArchive
   */
  count: any
}
